import turtle
import datetime
import time
om = turtle.Turtle()
om.color("green")
om.begin_fill()
om.forward(100)
om.left(90)
om.forward(100)
om.left(90)
om.forward(100)
om.left(90)
om.forward(100)
om.end_fill()

om.penup()
om.right(90)
om.forward(100)
om.pendown()
om.color("orange")
om.begin_fill()
om.forward(100)
om.right(90)
om.forward(100)
om.right(90)
om.forward(100)
om.right(90)
om.forward(100)
om.end_fill()
om.penup()
om.forward(25)
om.pendown()
om.color("green")
om.begin_fill()
om.left(90)
om.forward(100)
om.right(90)
om.forward(100)
om.right(90)
om.forward(100)
om.right(90)
om.forward(100)
om.end_fill()
om.penup()
om.forward(150)
om.pendown()
om.color("orange")
om.begin_fill()
om.forward(100)
om.right(90)
om.forward(100)
om.right(90)
om.forward(100)
om.right(90)
om.forward(100)
om.end_fill()
om.back(50)
om.left(90)
om.penup()
om.forward(50)
om.pendown()
om.color("blue")
om.begin_fill()
om.right(90)
om.forward(25)
om.left(90)
om.forward(50)
om.left(90)
om.forward(50)
om.left(90)
om.forward(50)
om.left(90)
om.forward(25)
om.end_fill()

#stw = int(datetime.datetime.now().strftime("%S"))
#print(stw)
#k =  stw + 2
#while True:
#    stw = int(datetime.datetime.now().strftime("%S"))
#    if k == int(stw):
#        exit()